// <auto-generated />
namespace StomatologyAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_order_and_procedure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_order_and_procedure));
        
        string IMigrationMetadata.Id
        {
            get { return "201605212205292_change_order_and_procedure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
