// <auto-generated />
namespace StomatologyAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fix_user_to_doctor_relation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_user_to_doctor_relation));
        
        string IMigrationMetadata.Id
        {
            get { return "201605140943012_fix_user_to_doctor_relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
