// <auto-generated />
namespace StomatologyAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class i_dont_know_what_changed_in_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(i_dont_know_what_changed_in_db));
        
        string IMigrationMetadata.Id
        {
            get { return "201605142245495_i_dont_know_what_changed_in_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
